#!/bin/python3

'''
It looks like someone messed up my picture! Can anyone reorganize the pixels? 
The python module PIL (Python Imaging Library) might be useful! 
https://mega.nz/#!OKxByZyT!vaabCJRG5D9zAUp7drTekcA5pszu67r_TbQMtxEzqGE

Update: I think whoever messed up my image took every column of pixels and put them side by side. Update: I think the width of the image was 304 before they messed with it.
'''



from PIL import Image, ImageOps
import numpy as np

# Convert the original image into an np.array
original = Image.open('out_copy.jpg', 'r')
np_array = np.array(original, dtype=np.uint8)
width = 304

no_of_pixels = len(np_array[0])
#print('Total number of pixels: '+str(no_of_pixels))  # 27968
one_dimensional_array = np_array[0]
height = no_of_pixels//width
two_dimensional_array = [one_dimensional_array[i:i+92] for i in range(0, len(one_dimensional_array), height)]
#print("Width of 2D array: "+str(len(two_dimensional_array)))  # 304

# Convert the np.array into an output image
np_array = np.array(two_dimensional_array, dtype=np.uint8)
output = Image.fromarray(np_array)


#Flip and rotate
flipped = ImageOps.mirror(output)
rotated = flipped.transpose(Image.ROTATE_90)

rotated.save("output.jpg")
